# Generated by Django 5.2.3 on 2025-06-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título ou nome do imóvel(Ex: Casa em Paraty)', max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do imóvel')),
                ('endereco', models.CharField(help_text='Endereço completo do imóvel', max_length=200)),
                ('tipo', models.CharField(choices=[('AP', 'Apartamento'), ('CA', 'Casa'), ('SA', 'Sala'), ('LJ', 'Loja'), ('SBJ', 'Sobreloja'), ('GP', 'Galpão'), ('TE', 'Terreno'), ('PT', 'Parte')], default='CA', help_text='Tipo do Imóvel', max_length=3)),
                ('preco', models.DecimalField(decimal_places=2, help_text='Valor do imóvel (Ex.: 1000000,00).', max_digits=10)),
                ('disponivel', models.BooleanField(default=True, help_text='Se está disponível para venda ou locação.')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, help_text='Data em que o imóvel foi cadastrado.')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Data da ultima atualização.')),
            ],
        ),
    ]
