# Generated by Django 5.2.3 on 2025-06-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do Locador', max_length=100)),
                ('cpf_cnpj', models.CharField(help_text='Digite o CPF ou CNPJ', max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Email para contato', max_length=254)),
                ('telefone', models.CharField(blank=True, help_text='Telefone para contato', max_length=20)),
                ('endereco', models.CharField(blank=True, help_text='Endereço Locador', max_length=200)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, help_text='Data que o locador fo cadastrado')),
            ],
        ),
    ]
