# Generated by Django 5.2.3 on 2025-06-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_locador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('F', 'Pessoa Fisíca'), ('J', 'Pessoa Jurídica')], default='F', help_text='Tipo de Pessoa: Fisíca ou Jurídica', max_length=1)),
                ('nome', models.CharField(help_text='Nome completo do Locador', max_length=100)),
                ('cpf', models.CharField(help_text='Digite o CPF do Locador', max_length=13, unique=True)),
                ('identidade', models.CharField(blank=True, help_text='Documento de Identificação com Foto', max_length=30, null=True)),
                ('cnpj', models.CharField(help_text='Digite o CNPJ da Empresa', max_length=18, unique=True)),
                ('inscricao_estadual', models.CharField(blank=True, help_text='Inscrição estadual empresa', max_length=30, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email para contato', max_length=254)),
                ('telefone', models.CharField(blank=True, help_text='Telefone para contato', max_length=20)),
                ('endereco', models.CharField(blank=True, help_text='Endereço Locador', max_length=200)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, help_text='Data que o locador fo cadastrado')),
            ],
        ),
        migrations.DeleteModel(
            name='Locador',
        ),
    ]
