# Generated by Django 5.2.3 on 2025-06-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0004_locatarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Fiador', max_length=100)),
                ('cpf', models.CharField(help_text='Digite o CPF do Fiador.', max_length=13, unique=True)),
                ('identidade', models.CharField(blank=True, help_text='Documento de identificação com foto.', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
