# Generated by Django 5.2.3 on 2025-06-25 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0005_fiadores'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocadorImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participacao', models.DecimalField(decimal_places=2, help_text='Percentual de Participação de Locação do Imóvel.', max_digits=5)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imoveis.imovel')),
                ('locador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imoveis.locadores')),
            ],
            options={
                'unique_together': {('imovel', 'locador')},
            },
        ),
        migrations.AddField(
            model_name='imovel',
            name='locadores',
            field=models.ManyToManyField(help_text='Locadores Vinculados a esse imóvel', related_name='imoveis', through='imoveis.LocadorImovel', to='imoveis.locadores'),
        ),
    ]
