# Generated by Django 5.2.3 on 2025-06-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0006_locadorimovel_imovel_locadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locadores',
            name='cnpj',
            field=models.CharField(blank=True, help_text='Digite o CNPJ da Empresa', max_length=18, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='locadores',
            name='cpf',
            field=models.CharField(blank=True, help_text='Digite o CPF do Locador', max_length=13, null=True, unique=True),
        ),
    ]
