# Generated by Django 5.2.3 on 2025-06-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0007_alter_locadores_cnpj_alter_locadores_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locatarios',
            name='cnpj',
            field=models.CharField(blank=True, help_text='Digite o CNPJ da empresa.', max_length=18, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='locatarios',
            name='cpf',
            field=models.CharField(blank=True, help_text='Digite o CPF do Locador.', max_length=13, null=True, unique=True),
        ),
    ]
