# Generated by Django 5.2.3 on 2025-06-25 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0008_alter_locatarios_cnpj_alter_locatarios_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='fiador',
            field=models.ForeignKey(blank=True, help_text='Fiador do Locatario se houver', null=True, on_delete=django.db.models.deletion.SET_NULL, to='imoveis.fiadores'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='locatario',
            field=models.ForeignKey(blank=True, help_text='Locatário atual do imóvel(se alugado)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='imoveis.locatarios'),
        ),
    ]
