# Generated by Django 5.2.3 on 2025-06-26 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0009_imovel_fiador_imovel_locatario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoLocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('valor_aluguel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodo_reajuste', models.CharField(choices=[('ANUAL', 'Anual'), ('SEMESTRAL', 'Semestral'), ('TRIENAL', 'Trienal')], default='ANUAL', max_length=20)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('E', 'Encerrado'), ('R', 'Rescidido')], default='ATIVO', max_length=15)),
                ('observacoes', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('fiador', models.ForeignKey(blank=True, help_text='Fiador, responsavel pelo pagamento se nao houver(opcinal)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='imoveis.fiadores')),
                ('imovel', models.ForeignKey(help_text='Imóvel alugado por este contrato.', on_delete=django.db.models.deletion.PROTECT, to='imoveis.imovel')),
                ('locatario', models.ForeignKey(help_text='Pessoa ou empresa que esta alugando o imóvel', on_delete=django.db.models.deletion.PROTECT, to='imoveis.locatarios')),
            ],
        ),
    ]
