# Generated by Django 5.2.3 on 2025-06-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0010_contratolocacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratolocacao',
            name='tipo',
            field=models.CharField(choices=[('RESIDENCIAL', 'Residencial'), ('NAO_RESIDENCIAL', 'Não Residencial'), ('COMERCIAL', 'Comercial')], default='RESIDENCIAL', max_length=30),
        ),
    ]
