# Generated by Django 5.2.3 on 2025-06-26 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0011_contratolocacao_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContratoLocacao',
        ),
    ]
